### ISSUE TITLE
[QUESTION] Works with Dolphin 5.0 + on MAC OS???

### ISSUE THREAD

**Issue by Rob-Rychs** [pmarcus93/xbox-controller-profiles-for-dolphin-emu#2]
Hi @pmarcus93 ,

I'm trying to use these profiles on XBOX ONE controller + Dolphin 5.0 for MAC OS but I'm having a tough time finding the right /config folder to put the profile in... Do you have any idea where it's at? Not in my Applicationsupport/ folder...

Appreciate any help.

Thanks

**Comment by Rob-Rychs** [comment]
I found the Dolphin/ folder. Tried creating a /Profile folder inside the /Config folder because there wasn't one and moved the file there but it didn't work, tried taking it out of the /Profile folder and putting the xbox-profile.ini just inside the /Config folder but it's still not displaying from the select drop down inside Dolphin controller settings GUI...

**Comment by pmarcus93** [comment]
Hi, @Rob-Rychs!

I've checked with a friend who has a Mac and unfortunately, MacOS sees Xbox Controllers in a different way than Windows does (making the config files incompatible between the two OS). I already updated the readme.md to make it clear.

BTW, I've asked him to sent me a MacOS compatible version of my Platformers - Horizontal Wiimote config. [Just download the file](https://gist.github.com/pmarcus93/b28fc3d5b26fd881693164ec1acb9fd0) and place it on the config folder. The path on MacOS is /Users/yourusername/Library/Application Support/Dolphin/Config/Profiles/Wiimote.

Feel free to contact me if you still have any issues. 😄

**Comment by Rob-Rychs** [comment]
Thanks @pmarcus93! 
That file and path worked like a charm on MACOS High Sierra! 🙌  
If you want to further update the README.md with the correct file/instructions for MAC OS from this issue I'm sure it'll help some more people since I think easy and intuitive controller binding solutions  are the only thing really lacking on Dolphin 5.0... especially when compared  with platforms like openemu... If you want to assign this to me 👍
Thanks so much for helping me get set up!
Running a Nintendo wii console on a Mac OS playing with a XBOX ONE controller... I don't think I'd believe it was possible if I wasn't playing it myself... 😀
